---
title: "Untitled"
author: "Francisco Javier Lobo Cabrera"
date: "January 18th, 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

# INSERT HERE YOUR LOCAL DIRECTORY WHERE THE REPOSITORY WAS CLONED INTO:
local_directory = "C:\\Users\\usuario\\Desktop\\prueba\\"

# NOTE: PLACE YOUR NEW pdb_id_Q_and_len.txt INSIDE clustering_trait_proteins/data_analysis/already_computed_results/
# TO RENDER THE RESULTS WITH YOUR EXECUTION

# Obtain data of pdb_id_Q_and_len.txt:
datos <- read.table(file.path(local_directory, "clustering_trait_proteins", "data_analysis", "already_computed_results", "pdb_id_Q_and_len.txt"), header=FALSE)
```

```{r}

# Count rows before filtering
rows_before <- nrow(datos)

# Filter the dataframe (discard outliers)
datos <- datos[datos$V2/datos$V3 <= 1.032, ]

# Count rows after filtering
rows_after <- nrow(datos)

# Print the counts
print(paste("Rows before filtering:", rows_before))
print(paste("Rows after filtering:", rows_after))

datos_write = datos
colnames(datos_write) <- NULL  # Remove column names 
write.csv(datos_write,file.path(local_directory, "clustering_trait_proteins", "data_analysis", "already_computed_results", "pdb_id_Q_and_len_no-outliers.txt"), row.names=FALSE,col.names=FALSE, quote=FALSE)  


# Discard rows with Nans
datos <- na.omit(datos)
print(nrow(datos))
# Also discard rows where Q1 = 0
datos <- subset(datos, V2 > 0)
print(nrow(datos))
```


```{r}
# Generate linear model and obtain coefficients and R²

datos$V4 <- datos$V3^2

modelo_lineal <- lm(datos$V2 ~ datos$V3 + datos$V4 - 1) # -1 is for forcing the dataset not to have an intercept (it actually makes more sense that it does not have an intercept, and it increases R²)


summary(modelo_lineal)

number_entries = as.character(nrow(datos))
coefficients <- coef(modelo_lineal)
coef_v3 <- as.character(round(coefficients["datos$V3"], 5))
coef_v4 <- as.character(round(coefficients["datos$V4"], 5)) #At least round to 5 decimals because it is that order of magnitude.
r_squared <- as.character(round(summary(modelo_lineal)$r.squared, 5))

```


```{r}
# Print the plot of empirical law
library(ggplot2)

# Generate predicted values using the modelo_lineal model
predicted_values <- predict(modelo_lineal, newdata = datos)

# Create a dataframe with V3, V2, and predicted_values
plot_data <- data.frame(V3 = datos$V3, V2 = datos$V2, predicted_values = predicted_values)

# Scatter plot with linear regression prediction line
plot <- ggplot(plot_data, aes(x = V3, y = V2)) +
  geom_jitter(alpha = 0.3) +  # Scatter plot with light grey points that get darker as they stack
  geom_line(aes(y = predicted_values), color = "red") +  # Linear regression prediction line
  labs(x = "n", y = "Q (Å⁻²)") +
  theme_minimal() +
  annotate("text", x = median(plot_data$V3), y = max(plot_data$V2), 
           label = paste0("Q ≈ ", coef_v3, "n + ", coef_v4, "n²\nTotal entries: ", number_entries, "\nR² = ", r_squared), 
           hjust = 0, vjust = 1, color = "black", size = 5)

# Print the plot
print(plot)

```


```{r}
# Obtain average composition of each residue type in the set of PDB proteins

# NOTE: PLACE YOUR NEW pdb_id_residue_percentages.txt INSIDE clustering_trait_proteins/data_analysis/already_computed_results/
# TO RENDER THE RESULTS WITH YOUR EXECUTION

# Step 1: Read file with the composition of each PDB entry
df <- read.table(file.path(local_directory, "clustering_trait_proteins", "data_analysis", "already_computed_results", "pdb_id_residue_percentages.txt"), header=TRUE, sep="\t")


print(head(df))

# Step 2: Create a new version of df where columns 2 to 6 are converted to numeric
df_numeric <- df
df_numeric[, 2:6] <- lapply(df_numeric[, 2:6], function(col) as.numeric(as.character(col)))

print(head(df_numeric))

# Step 3: Calculate the average of each numeric column (from 2nd to 6th column)
column_averages <- colMeans(df_numeric[, 2:6], na.rm = TRUE)

# Step 4: Create a named output for the column names and their respective means
averages_with_names <- data.frame(Column = colnames(df_numeric)[2:6], Mean = column_averages)

# Step 5: Display the result
print(averages_with_names)


```
```{r}
# Obtain average and quartiles Q1 and Q3 of residue density in PDB structures
# NOTE: PLACE YOUR NEW pdb_id_and_compactness.txt INSIDE clustering_trait_proteins/data_analysis/already_computed_results/
# TO RENDER THE RESULTS WITH YOUR EXECUTION

# Step 1: Read file with residue density (compactness) in sphere
df_density <- read.table(file.path(local_directory, "clustering_trait_proteins", "data_analysis", "already_computed_results", "pdb_id_and_compactness.txt"), header=FALSE, sep="\t")

# Calculate density in cube
df_density$den_cube = df_density$V2*3.1416/6


Q1 <- quantile(df_density$den_cube, 0.25, na.rm = TRUE)  # 25th percentile (Q1)
Q3 <- quantile(df_density$den_cube, 0.75, na.rm = TRUE)  # 75th percentile (Q3)
den_average <- mean(df_density$den_cube, na.rm = TRUE)

# Print the results
print(paste("Q1 (25th percentile):", Q1))
print(paste("Q3 (75th percentile):", Q3))
print(den_average)
```

```{r}
# Models from stochastic simulations

# NOTE: TO RENDER RESULTS WITH YOUR EXECUTION PLACE YOUR NEW Q1_and_number_of_residues_imaginary_protein.txt OF EACH CASE INSIDE THE CORRESPONDING DIRECTORY.
# FOR EXAMPLE, IF YOU HAVE EXECUTED FOR SHAPE I / CLUSTERING SIZE 6, THEN REPLACE THE FILE clustering_trait_proteins/simulation/shape_I/already_computed_results/shape_I_clustering_size_6/Q1_and_number_of_residues_imaginary_protein.txt 
# WITH YOUR NEWLY GENERATED Q1_and_number_of_residues_imaginary_protein.txt



########################################################################################################################
datos_shape_I_cluster_size_6 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_I", "already_computed_results", "shape_I_cluster_size_6", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_I_cluster_size_6 <- lm(datos_shape_I_cluster_size_6$V1 ~ datos_shape_I_cluster_size_6$V2 - 1)
r_squared_shape_I_cluster_size_6 <- as.character(round(summary(modelo_lineal_shape_I_cluster_size_6)$r.squared, 3))

predicted_values_shape_I_cluster_size_6 <- predict(modelo_lineal_shape_I_cluster_size_6, newdata = datos_shape_I_cluster_size_6)

########################################################################################################################
datos_shape_I_cluster_size_7 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_I", "already_computed_results", "shape_I_cluster_size_7", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_I_cluster_size_7 <- lm(datos_shape_I_cluster_size_7$V1 ~ datos_shape_I_cluster_size_7$V2 - 1)
r_squared_shape_I_cluster_size_7 <- as.character(round(summary(modelo_lineal_shape_I_cluster_size_7)$r.squared, 3))

predicted_values_shape_I_cluster_size_7 <- predict(modelo_lineal_shape_I_cluster_size_7, newdata = datos_shape_I_cluster_size_7)

########################################################################################################################
datos_shape_I_cluster_size_8 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_I", "already_computed_results", "shape_I_cluster_size_8", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_I_cluster_size_8 <- lm(datos_shape_I_cluster_size_8$V1 ~ datos_shape_I_cluster_size_8$V2 - 1)
r_squared_shape_I_cluster_size_8 <- as.character(round(summary(modelo_lineal_shape_I_cluster_size_8)$r.squared, 3))

predicted_values_shape_I_cluster_size_8 <- predict(modelo_lineal_shape_I_cluster_size_8, newdata = datos_shape_I_cluster_size_8)

########################################################################################################################
datos_shape_I_cluster_size_11 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_I", "already_computed_results", "shape_I_cluster_size_11", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_I_cluster_size_11 <- lm(datos_shape_I_cluster_size_11$V1 ~ datos_shape_I_cluster_size_11$V2 - 1)
r_squared_shape_I_cluster_size_11 <- as.character(round(summary(modelo_lineal_shape_I_cluster_size_11)$r.squared, 3))

predicted_values_shape_I_cluster_size_11 <- predict(modelo_lineal_shape_I_cluster_size_11, newdata = datos_shape_I_cluster_size_11)

########################################################################################################################
datos_shape_I_cluster_size_12 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_I", "already_computed_results", "shape_I_cluster_size_12", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_I_cluster_size_12 <- lm(datos_shape_I_cluster_size_12$V1 ~ datos_shape_I_cluster_size_12$V2 - 1)
r_squared_shape_I_cluster_size_12 <- as.character(round(summary(modelo_lineal_shape_I_cluster_size_12)$r.squared, 3))

predicted_values_shape_I_cluster_size_12 <- predict(modelo_lineal_shape_I_cluster_size_12, newdata = datos_shape_I_cluster_size_12)

########################################################################################################################
datos_shape_II_cluster_size_6 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_II", "already_computed_results", "shape_II_cluster_size_6", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_II_cluster_size_6 <- lm(datos_shape_II_cluster_size_6$V1 ~ datos_shape_II_cluster_size_6$V2 - 1)
r_squared_shape_II_cluster_size_6 <- as.character(round(summary(modelo_lineal_shape_II_cluster_size_6)$r.squared, 3))

predicted_values_shape_II_cluster_size_6 <- predict(modelo_lineal_shape_II_cluster_size_6, newdata = datos_shape_II_cluster_size_6)

########################################################################################################################

datos_shape_II_cluster_size_15 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_II", "already_computed_results", "shape_II_cluster_size_15", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_II_cluster_size_15 <- lm(datos_shape_II_cluster_size_15$V1 ~ datos_shape_II_cluster_size_15$V2 - 1)
r_squared_shape_II_cluster_size_15 <- as.character(round(summary(modelo_lineal_shape_II_cluster_size_15)$r.squared, 3))

predicted_values_shape_II_cluster_size_15 <- predict(modelo_lineal_shape_II_cluster_size_15, newdata = datos_shape_II_cluster_size_15)

########################################################################################################################
datos_shape_II_cluster_size_20 <- read.table(file.path(local_directory, "clustering_trait_proteins", "simulation", "shape_II", "already_computed_results", "shape_II_cluster_size_20", "Q1_and_number_of_residues_imaginary_protein.txt"))

modelo_lineal_shape_II_cluster_size_20 <- lm(datos_shape_II_cluster_size_20$V1 ~ datos_shape_II_cluster_size_20$V2 - 1)
r_squared_shape_II_cluster_size_20 <- as.character(round(summary(modelo_lineal_shape_II_cluster_size_20)$r.squared, 3))

predicted_values_shape_II_cluster_size_20 <- predict(modelo_lineal_shape_II_cluster_size_20, newdata = datos_shape_II_cluster_size_20)


```

```{r}
# Calculation of RMSE of each simulation with experimental model

# Load necessary libraries
library(dplyr)
library(tidyr)
library(ggplot2)


# Extract V3 (number of residues) values from the experimental dataset to use as common X values
datos_aux = plot_data[plot_data$V3 <= 400, ] # select experimental proteins with fewer than 400 residues, since the simulations do not  contain more than 400 residues
common_x <- datos_aux$V3

# Train the model of each set of simulations
modelo_shape_I_cluster_size_6 <- lm(V1 ~ V2 - 1, data = datos_shape_I_cluster_size_6)
modelo_shape_I_cluster_size_7 <- lm(V1 ~ V2 - 1, data = datos_shape_I_cluster_size_7)
modelo_shape_I_cluster_size_8 <- lm(V1 ~ V2 - 1, data = datos_shape_I_cluster_size_8)
modelo_shape_I_cluster_size_11 <- lm(V1 ~ V2 - 1, data = datos_shape_I_cluster_size_11)
modelo_shape_I_cluster_size_12 <- lm(V1 ~ V2 - 1, data = datos_shape_I_cluster_size_12)
modelo_shape_II_cluster_size_6 <- lm(V1 ~ V2 - 1, data = datos_shape_II_cluster_size_6)
modelo_shape_II_cluster_size_15 <- lm(V1 ~ V2 - 1, data = datos_shape_II_cluster_size_15)
modelo_shape_II_cluster_size_20 <- lm(V1 ~ V2 - 1, data = datos_shape_II_cluster_size_20)


# Create newdata dataframes for each set of simulations
newdata_shape_I_cluster_size_6 <- data.frame(V2 = common_x)
newdata_shape_I_cluster_size_7 <- data.frame(V2 = common_x)
newdata_shape_I_cluster_size_8 <- data.frame(V2 = common_x)
newdata_shape_I_cluster_size_11 <- data.frame(V2 = common_x)
newdata_shape_I_cluster_size_12 <- data.frame(V2 = common_x)
newdata_shape_II_cluster_size_6 <- data.frame(V2 = common_x)
newdata_shape_II_cluster_size_15 <- data.frame(V2 = common_x)
newdata_shape_II_cluster_size_20 <- data.frame(V2 = common_x)


# Use the models to predict values at the common set of X values
predicted_experimental <- datos_aux$predicted_values
predicted_shape_I_cluster_size_11 <- predict(modelo_shape_I_cluster_size_11, newdata = newdata_shape_I_cluster_size_11)
predicted_shape_I_cluster_size_12 <- predict(modelo_shape_I_cluster_size_12, newdata = newdata_shape_I_cluster_size_12)
predicted_shape_I_cluster_size_8 <- predict(modelo_shape_I_cluster_size_8, newdata = newdata_shape_I_cluster_size_8)
predicted_shape_II_cluster_size_15 <- predict(modelo_shape_II_cluster_size_15, newdata = newdata_shape_II_cluster_size_15)
predicted_shape_II_cluster_size_20 <- predict(modelo_shape_II_cluster_size_20, newdata = newdata_shape_II_cluster_size_20)
predicted_shape_II_cluster_size_6 <- predict(modelo_shape_II_cluster_size_6, newdata = newdata_shape_II_cluster_size_6)
predicted_shape_I_cluster_size_7 <- predict(modelo_shape_I_cluster_size_7, newdata = newdata_shape_I_cluster_size_7)
predicted_shape_I_cluster_size_6 <- predict(modelo_shape_I_cluster_size_6, newdata = newdata_shape_I_cluster_size_6)

# Ensure all predicted values have the same length
stopifnot(length(predicted_experimental) == length(common_x))
stopifnot(length(predicted_shape_I_cluster_size_6) == length(common_x))
stopifnot(length(predicted_shape_I_cluster_size_7) == length(common_x))
stopifnot(length(predicted_shape_I_cluster_size_8) == length(common_x))
stopifnot(length(predicted_shape_I_cluster_size_11) == length(common_x))
stopifnot(length(predicted_shape_I_cluster_size_12) == length(common_x))
stopifnot(length(predicted_shape_II_cluster_size_6) == length(common_x))
stopifnot(length(predicted_shape_II_cluster_size_15) == length(common_x))
stopifnot(length(predicted_shape_II_cluster_size_20) == length(common_x))


# Calculate RMSE for each case relative to the experimental law
rmse_shape_I_cluster_size_6 <- sqrt(sum((predicted_shape_I_cluster_size_6 - predicted_experimental)^2) / length(common_x))
rmse_shape_I_cluster_size_7 <- sqrt(sum((predicted_shape_I_cluster_size_7 - predicted_experimental)^2) / length(common_x))
rmse_shape_I_cluster_size_8 <- sqrt(sum((predicted_shape_I_cluster_size_8 - predicted_experimental)^2) / length(common_x))
rmse_shape_I_cluster_size_11 <- sqrt(sum((predicted_shape_I_cluster_size_11 - predicted_experimental)^2) / length(common_x))
rmse_shape_I_cluster_size_12 <- sqrt(sum((predicted_shape_I_cluster_size_12 - predicted_experimental)^2) / length(common_x))
rmse_shape_II_cluster_size_6 <- sqrt(sum((predicted_shape_II_cluster_size_6 - predicted_experimental)^2) / length(common_x))
rmse_shape_II_cluster_size_15 <- sqrt(sum((predicted_shape_II_cluster_size_15 - predicted_experimental)^2) / length(common_x))
rmse_shape_II_cluster_size_20 <- sqrt(sum((predicted_shape_II_cluster_size_20 - predicted_experimental)^2) / length(common_x))


# Create a summary dataframe
rmse_summary <- data.frame(
   Configuration = c("Shape: I Cluster size: 11", "Shape: I Cluster size: 12", "Shape: I Cluster size: 8", 
                     "Shape: II Cluster size: 15", "Shape: II Cluster size: 20", "Shape: II Cluster size: 6",
                     "Shape: I Cluster size: 7", "Shape: I Cluster size: 6"),
   RMSE = c(rmse_shape_I_cluster_size_11, rmse_shape_I_cluster_size_12, rmse_shape_I_cluster_size_8, rmse_shape_II_cluster_size_15, rmse_shape_II_cluster_size_20, rmse_shape_II_cluster_size_6, rmse_shape_I_cluster_size_7, rmse_shape_I_cluster_size_6)
)


# Order the RMSE summary from lower to higher RMSE values
rmse_summary <- rmse_summary %>% arrange(RMSE)

# Print the RMSE summary
print(rmse_summary)

# Round and transform to string
rmse_shape_I_cluster_size_6 <- as.character(round(rmse_shape_I_cluster_size_6, 3))
rmse_shape_I_cluster_size_7 <- as.character(round(rmse_shape_I_cluster_size_7, 3))
rmse_shape_I_cluster_size_8 <- as.character(round(rmse_shape_I_cluster_size_8, 3))
rmse_shape_I_cluster_size_11 <- as.character(round(rmse_shape_I_cluster_size_11, 3))
rmse_shape_I_cluster_size_12 <- as.character(round(rmse_shape_I_cluster_size_12, 3))
rmse_shape_II_cluster_size_6 <- as.character(round(rmse_shape_II_cluster_size_6, 3))
rmse_shape_II_cluster_size_15 <- as.character(round(rmse_shape_II_cluster_size_15, 3))
rmse_shape_II_cluster_size_20 <- as.character(round(rmse_shape_II_cluster_size_20, 3))




```



```{r}
# Print plot with results

# Load necessary libraries
library(ggplot2)

# Generate predicted values using the experimental model
predicted_values <- predict(modelo_lineal, newdata = datos)

# Create a dataframe with V3, V2, and predicted_values
plot_data <- data.frame(V3 = datos$V3, V2 = datos$V2, predicted_values = predicted_values)

# Analogous approach for simulations
plot_data_shape_I_cluster_size_6 <- data.frame(V2 = datos_shape_I_cluster_size_6$V2, V1 = datos_shape_I_cluster_size_6$V1, predicted_values_shape_I_cluster_size_6 = predicted_values_shape_I_cluster_size_6)
plot_data_shape_I_cluster_size_7 <- data.frame(V2 = datos_shape_I_cluster_size_7$V2, V1 = datos_shape_I_cluster_size_7$V1, predicted_values_shape_I_cluster_size_7 = predicted_values_shape_I_cluster_size_7)

plot_data_shape_I_cluster_size_8 <- data.frame(V2 = datos_shape_I_cluster_size_8$V2, V1 = datos_shape_I_cluster_size_8$V1, predicted_values_shape_I_cluster_size_8 = predicted_values_shape_I_cluster_size_8)

plot_data_shape_I_cluster_size_11 <- data.frame(V2 = datos_shape_I_cluster_size_11$V2, V1 = datos_shape_I_cluster_size_11$V1, predicted_values_shape_I_cluster_size_11 = predicted_values_shape_I_cluster_size_11)
plot_data_shape_I_cluster_size_12 <- data.frame(V2 = datos_shape_I_cluster_size_12$V2, V1 = datos_shape_I_cluster_size_12$V1, predicted_values_shape_I_cluster_size_12 = predicted_values_shape_I_cluster_size_12)
plot_data_shape_II_cluster_size_6 <- data.frame(V2 = datos_shape_II_cluster_size_6$V2, V1 = datos_shape_II_cluster_size_6$V1, predicted_values_shape_II_cluster_size_6 = predicted_values_shape_II_cluster_size_6)
plot_data_shape_II_cluster_size_15 <- data.frame(V2 = datos_shape_II_cluster_size_15$V2, V1 = datos_shape_II_cluster_size_15$V1, predicted_values_shape_II_cluster_size_15 = predicted_values_shape_II_cluster_size_15)
plot_data_shape_II_cluster_size_20 <- data.frame(V2 = datos_shape_II_cluster_size_20$V2, V1 = datos_shape_II_cluster_size_20$V1, predicted_values_shape_II_cluster_size_20 = predicted_values_shape_II_cluster_size_20)



plot <- ggplot() +
  geom_line(data = plot_data, aes(x = V3, y = predicted_values, 
                                  color = paste0("Empirical law - R²: ", r_squared))) +
  geom_line(data = plot_data_shape_I_cluster_size_6, aes(x = V2, y = predicted_values_shape_I_cluster_size_6, 
                                                         color = paste0("Shape: I Cluster size: 6 - R²: ", 
                                                                        r_squared_shape_I_cluster_size_6, 
                                                                        " RMSE: ", 
                                                                        rmse_shape_I_cluster_size_6, 
                                                                        " Å⁻²"))) +
  geom_line(data = plot_data_shape_I_cluster_size_7, aes(x = V2, y = predicted_values_shape_I_cluster_size_7, 
                                                         color = paste0("Shape: I Cluster size: 7 - R²: ", 
                                                                        r_squared_shape_I_cluster_size_7, 
                                                                        " RMSE: ", 
                                                                        rmse_shape_I_cluster_size_7, 
                                                                        " Å⁻²"))) +
  geom_line(data = plot_data_shape_I_cluster_size_8, aes(x = V2, y = predicted_values_shape_I_cluster_size_8, 
                                                         color = paste0("Shape: I Cluster size: 8 - R²: ", 
                                                                        r_squared_shape_I_cluster_size_8, 
                                                                        " RMSE: ", 
                                                                        rmse_shape_I_cluster_size_8, 
                                                                        " Å⁻²"))) +
  geom_line(data = plot_data_shape_I_cluster_size_11, aes(x = V2, y = predicted_values_shape_I_cluster_size_11, 
                                                          color = paste0("Shape: I Cluster size: 11 - R²: ", 
                                                                         r_squared_shape_I_cluster_size_11, 
                                                                         " RMSE: ", 
                                                                         rmse_shape_I_cluster_size_11, 
                                                                         " Å⁻²"))) +
  geom_line(data = plot_data_shape_I_cluster_size_12, aes(x = V2, y = predicted_values_shape_I_cluster_size_12, 
                                                          color = paste0("Shape: I Cluster size: 12 - R²: ", 
                                                                         r_squared_shape_I_cluster_size_12, 
                                                                         " RMSE: ", 
                                                                         rmse_shape_I_cluster_size_12, 
                                                                         " Å⁻²"))) +
  geom_line(data = plot_data_shape_II_cluster_size_6, aes(x = V2, y = predicted_values_shape_II_cluster_size_6, 
                                                          color = paste0("Shape: II Cluster size: 6 - R²: ", 
                                                                         r_squared_shape_II_cluster_size_6, 
                                                                         " RMSE: ", 
                                                                         rmse_shape_II_cluster_size_6, 
                                                                         " Å⁻²"))) +
  geom_line(data = plot_data_shape_II_cluster_size_15, aes(x = V2, y = predicted_values_shape_II_cluster_size_15, 
                                                           color = paste0("Shape: II Cluster size: 15 - R²: ", 
                                                                          r_squared_shape_II_cluster_size_15, 
                                                                          " RMSE: ", 
                                                                          rmse_shape_II_cluster_size_15, 
                                                                          " Å⁻²"))) +
  geom_line(data = plot_data_shape_II_cluster_size_20, aes(x = V2, y = predicted_values_shape_II_cluster_size_20, 
                                                           color = paste0("Shape: II Cluster size: 20 - R²: ", 
                                                                          r_squared_shape_II_cluster_size_20, 
                                                                          " RMSE: ", 
                                                                          rmse_shape_II_cluster_size_20, 
                                                                          " Å⁻²"))) +
  theme_minimal() +
  labs(x = "n", y = "Q (Å⁻²)", color = "Configurations") +  # Set a title for the legend
  xlim(0, 400) +  # Set fixed x-axis limits
  ylim(0, 300) +  # Set fixed y-axis limits
  theme(legend.position = "right", 
        legend.text = element_text(size = 8),
        legend.key.height = unit(1, "cm"))



# Print the plot
print(plot)


```



